---------------------------------------------------------------------
-- DbProject - Release Script
---------------------------------------------------------------------
-- Version:					1.3.0.0
-- Generated date:			26/06/2013
-- Generated on:			DESKTOP0317
-- Generated by:			mball
--
-- IMPORTANT! 
-- Before executing this script, you should really take a backup of 
-- the target database.
---------------------------------------------------------------------

SET IMPLICIT_TRANSACTIONS, NUMERIC_ROUNDABORT OFF;
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, NOCOUNT, QUOTED_IDENTIFIER ON;
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET XACT_ABORT ON;

BEGIN TRY
BEGIN TRANSACTION trans_Deployment;





---------------------------------------------------------------------
-- 0001_create_table_House.sql
---------------------------------------------------------------------
GO

CREATE TABLE [dbo].[House] (
	[HouseId]			[int]			IDENTITY(1,1),
	[HouseNumber]			[nvarchar](10)		NOT NULL,
	[AddressLine1]			[nvarchar](100)		NOT NULL,
	[AddressLine2]			[nvarchar](100)		NULL,
	[AddressLine3]			[nvarchar](100)		NULL,
	[PostalCode]			[nvarchar](10)		NOT NULL,

	CONSTRAINT [PK_House] PRIMARY KEY CLUSTERED
	(
		[HouseId]					ASC
	)
)
GO

EXEC [dbo].[up_DeploymentLog_Insert] 'DbProject-1.3.0.0', '0001_create_table_House.sql', 'SUCCESS', '0001_create_table_House.sql was deployed successfully', SYSTEM_USER

---------------------------------------------------------------------





GO
COMMIT TRANSACTION trans_Deployment;

EXEC [dbo].[up_Deployment_Insert] 'DbProject-1.3.0.0', 'deploy.sql', 'N/A'

END TRY
BEGIN CATCH

ROLLBACK TRANSACTION trans_Deployment;

SELECT ERROR_NUMBER() AS [ErrorNumber], ERROR_SEVERITY() AS [ErrorSeverity], ERROR_STATE() AS [ErrorState], ERROR_MESSAGE() AS [ErrorMessage]

END CATCH

SET NOEXEC OFF;