---------------------------------------------------------------------
-- DbProject - Release Script
---------------------------------------------------------------------
-- Version:					1.1.0.0
-- Generated date:			24/06/2013
-- Generated on:			DESKTOP0317
-- Generated by:			mball
--
-- IMPORTANT! 
-- Before executing this script, you should really take a backup of 
-- the target database.
---------------------------------------------------------------------

SET IMPLICIT_TRANSACTIONS, NUMERIC_ROUNDABORT OFF;
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, NOCOUNT, QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;


---------------------------------------------------------------------
-- 0001_create_table_Product.sql
---------------------------------------------------------------------
GO

CREATE TABLE [dbo].[Product]
(
	[ProductId]			[int] 			IDENTITY(1,1) NOT FOR REPLICATION,
	[ProductName]			[nvarchar](100)		NOT NULL,
	[UnitPrice]			[decimal](12,2)		NOT NULL,

	CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED
	(
		[ProductId]					ASC
	)
)
GO


---------------------------------------------------------------------
-- 0002_create_table_ProductImage.sql
---------------------------------------------------------------------
GO

CREATE TABLE [dbo].[Product]
(
	[ProductId]			[int] 			IDENTITY(1,1) NOT FOR REPLICATION,
	[ProductName]			[nvarchar](100)		NOT NULL,
	[UnitPrice]			[decimal](12,2)		NOT NULL,

	CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED
	(
		[ProductId]					ASC
	)
)
GO



SET NOEXEC OFF;